/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : LED1_4.c
**     Project     : ProcessorExpert
**     Processor   : MKL25Z128VLK4
**     Component   : BitsIO
**     Version     : Component 02.108, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-03-15, 11:32, # CodeGen: 11
**     Abstract    :
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
**     Settings    :
**         Port name                   : PTB
**
**         Bit mask of the port        : 0x000F
**         Number of bits/pins         : 4
**         Single bit numbers          : 0 to 3
**         Values range                : 0 to 15
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         Port data register          : GPIOB_PDOR [0x400FF040]
**         Port control register       : GPIOB_PDDR [0x400FF054]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    43   |   ADC0_SE8/TSI0_CH0/PTB0/LLWU_P5/I2C0_SCL/TPM1_CH0
**                    1      |    44   |   ADC0_SE9/TSI0_CH6/PTB1/I2C0_SDA/TPM1_CH1
**                    2      |    45   |   ADC0_SE12/TSI0_CH7/PTB2/I2C0_SCL/TPM2_CH0
**                    3      |    46   |   ADC0_SE13/TSI0_CH8/PTB3/I2C0_SDA/TPM2_CH1
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents    :
**         GetDir - bool LED1_4_GetDir(void);
**         GetVal - byte LED1_4_GetVal(void);
**         PutVal - void LED1_4_PutVal(byte Val);
**         GetBit - bool LED1_4_GetBit(byte Bit);
**         PutBit - void LED1_4_PutBit(byte Bit, bool Val);
**         SetBit - void LED1_4_SetBit(byte Bit);
**         ClrBit - void LED1_4_ClrBit(byte Bit);
**         NegBit - void LED1_4_NegBit(byte Bit);
**
**     Copyright : 1997 - 2012 Freescale, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE LED1_4. */

#include "LED1_4.h"

/*
** ===================================================================
**     Method      :  LED1_4_GetDir (component BitsIO)
**
**     Description :
**         This method returns direction of the component.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the component (always TRUE, Output only)
**                      FALSE = Input, TRUE = Output
** ===================================================================
*/
/*
bool LED1_4_GetDir(void)

**  This method is implemented as a macro. See LED1_4.h file.  **
*/

/*
** ===================================================================
**     Method      :  LED1_4_GetVal (component BitsIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 15)
** ===================================================================
*/
/*
byte LED1_4_GetVal(void)

**  This method is implemented as a macro. See LED1_4.h file.  **
*/

/*
** ===================================================================
**     Method      :  LED1_4_PutVal (component BitsIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 15)
**     Returns     : Nothing
** ===================================================================
*/
/*
void LED1_4_PutVal(byte Val)

**  This method is implemented as a macro. See LED1_4.h file.  **
*/

/*
** ===================================================================
**     Method      :  LED1_4_GetBit (component BitsIO)
**
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 3)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool LED1_4_GetBit(byte Bit)
{
  bool BitVal;

  (void)BitsIoLdd3_GetBit(BitsIoLdd3_DeviceData, Bit, &BitVal);
  return (BitVal);
}

/*
** ===================================================================
**     Method      :  LED1_4_PutBit (component BitsIO)
**
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 3)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
/*
void LED1_4_PutBit(byte Bit, bool Val)

**  This method is implemented as a macro. See LED1_4.h file.  **
*/

/*
** ===================================================================
**     Method      :  LED1_4_SetBit (component BitsIO)
**
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
/*
void LED1_4_SetBit(byte Bit)

**  This method is implemented as a macro. See LED1_4.h file.  **
*/

/*
** ===================================================================
**     Method      :  LED1_4_ClrBit (component BitsIO)
**
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
/*
void LED1_4_ClrBit(byte Bit)

**  This method is implemented as a macro. See LED1_4.h file.  **
*/

/*
** ===================================================================
**     Method      :  LED1_4_NegBit (component BitsIO)
**
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
/*
void LED1_4_NegBit(byte Bit)

**  This method is implemented as a macro. See LED1_4.h file.  **
*/

/* END LED1_4. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
