/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : RegelungReferenztimer.h
**     Project     : ProcessorExpert
**     Processor   : MKL25Z128VLK4
**     Component   : TimerUnit_LDD
**     Version     : Component 01.137, Driver 01.08, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-03-15, 11:32, # CodeGen: 11
**     Abstract    :
**          This TimerUnit component provides a low level API for unified hardware access across
**          various timer devices using the Prescaler-Counter-Compare-Capture timer structure.
**     Settings    :
**          Component name                                 : RegelungReferenztimer
**          Module name                                    : SysTick
**          Counter                                        : SYST_CVR
**          Counter direction                              : Down
**          Counter width                                  : 24 bits
**          Value type                                     : Optimal
**          Input clock source                             : Internal
**            Counter frequency                            : 1.31072 MHz
**          Counter restart                                : On-match
**            Period device                                : SYST_RVR
**            Period                                       : 1 ms
**            Interrupt                                    : Enabled
**              Interrupt                                  : INT_SysTick
**              Interrupt priority                         : medium priority
**          Channel list                                   : 0
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Auto initialization                          : yes
**            Event mask                                   : 
**              OnCounterRestart                           : Enabled
**              OnChannel0                                 : Disabled
**              OnChannel1                                 : Disabled
**              OnChannel2                                 : Disabled
**              OnChannel3                                 : Disabled
**              OnChannel4                                 : Disabled
**              OnChannel5                                 : Disabled
**              OnChannel6                                 : Disabled
**              OnChannel7                                 : Disabled
**          CPU clock/configuration selection              : 
**            Clock configuration 0                        : This component enabled
**            Clock configuration 1                        : This component disabled
**            Clock configuration 2                        : This component disabled
**     Contents    :
**         Init   - LDD_TDeviceData* RegelungReferenztimer_Init(LDD_TUserData *UserDataPtr);
**         Deinit - void RegelungReferenztimer_Deinit(LDD_TDeviceData *DeviceDataPtr);
**
**     Copyright : 1997 - 2012 Freescale, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __RegelungReferenztimer_H
#define __RegelungReferenztimer_H

/* MODULE RegelungReferenztimer. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */

#include "PE_LDD.h"
#include "SysTick_PDD.h"
#include "Cpu.h"


#ifndef __BWUserType_RegelungReferenztimer_TValueType
#define __BWUserType_RegelungReferenztimer_TValueType
  typedef uint32_t RegelungReferenztimer_TValueType ; /* Type for data parameters of methods */
#endif
#define RegelungReferenztimer_CNT_INP_FREQ_U_0 0x00140000UL /* Counter input frequency in Hz */
#define RegelungReferenztimer_CNT_INP_FREQ_R_0 1310720.778463285F /* Counter input frequency in Hz */
#define RegelungReferenztimer_CNT_INP_FREQ_COUNT 0U /* Count of predefined counter input frequencies */
#define RegelungReferenztimer_PERIOD_TICKS 0x051FUL /* Initialization value of period in 'counter ticks' */
#define RegelungReferenztimer_NUMBER_OF_CHANNELS 0x00U /* Count of predefined channels */
#define RegelungReferenztimer_COUNTER_WIDTH 0x18U /* Counter width in bits  */
#define RegelungReferenztimer_COUNTER_DIR DIR_DOWN /* Direction of counting */
/* Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros. */
#define RegelungReferenztimer_PRPH_BASE_ADDRESS  0xE000E010U
  
/* Device data structure pointer used when auto initialization property is enabled. This constant can be passed as a first parameter to all component's methods. */
#define RegelungReferenztimer_DeviceData  ((LDD_TDeviceData *)PE_LDD_GetDeviceStructure(PE_LDD_COMPONENT_RegelungReferenztimer_ID))

/* Methods configuration constants - generated for all enabled component's methods */
#define RegelungReferenztimer_Init_METHOD_ENABLED
#define RegelungReferenztimer_Deinit_METHOD_ENABLED

/* Events configuration constants - generated for all enabled component's events */
#define RegelungReferenztimer_OnCounterRestart_EVENT_ENABLED



LDD_TDeviceData* RegelungReferenztimer_Init(LDD_TUserData *UserDataPtr);
/*
** ===================================================================
**     Method      :  RegelungReferenztimer_Init (component TimerUnit_LDD)
**
**     Description :
**         Initializes the device. Allocates memory for the device data
**         structure, allocates interrupt vectors and sets interrupt
**         priority, sets pin routing, sets timing, etc. If the
**         property <"Enable in init. code"> is set to "yes" value then
**         the device is also enabled (see the description of the
**         <Enable> method). In this case the <Enable> method is not
**         necessary and needn't to be generated. This method can be
**         called only once. Before the second call of Init the <Deinit>
**         must be called first.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     Returns     :
**         ---             - Pointer to the dynamically allocated
**                           private structure or NULL if there was an
**                           error.
** ===================================================================
*/

void RegelungReferenztimer_Deinit(LDD_TDeviceData *DeviceDataPtr);
/*
** ===================================================================
**     Method      :  RegelungReferenztimer_Deinit (component TimerUnit_LDD)
**
**     Description :
**         Deinitializes the device. Switches off the device, frees the
**         device data structure memory, interrupts vectors, etc.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * DeviceDataPtr   - Device data structure
**                           pointer returned by Init method
**     Returns     : Nothing
** ===================================================================
*/

/* {Default RTOS Adapter} ISR function prototype */
PE_ISR(RegelungReferenztimer_Interrupt);
/*
** ===================================================================
**     Method      :  RegelungReferenztimer_Interrupt (component TimerUnit_LDD)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

/* END RegelungReferenztimer. */

#endif
/* ifndef __RegelungReferenztimer_H */
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
