/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : US_Triger.h
**     Project     : ProcessorExpert
**     Processor   : MKL25Z128VLK4
**     Component   : BitsIO
**     Version     : Component 02.108, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-03-15, 11:32, # CodeGen: 11
**     Abstract    :
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
**     Settings    :
**         Port name                   : PTE
**
**         Bit mask of the port        : 0x003C
**         Number of bits/pins         : 4
**         Single bit numbers          : 0 to 3
**         Values range                : 0 to 15
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 15 = 00FH
**         Initial pull option         : off
**
**         Port data register          : GPIOE_PDOR [0x400FF100]
**         Port control register       : GPIOE_PDDR [0x400FF114]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    3    |   PTE2/SPI1_SCK
**                    1      |    4    |   PTE3/SPI1_MISO/SPI1_MOSI
**                    2      |    5    |   PTE4/SPI1_PCS0
**                    3      |    6    |   PTE5
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents    :
**         GetDir - bool US_Triger_GetDir(void);
**         GetVal - byte US_Triger_GetVal(void);
**         PutVal - void US_Triger_PutVal(byte Val);
**         GetBit - bool US_Triger_GetBit(byte Bit);
**         PutBit - void US_Triger_PutBit(byte Bit, bool Val);
**         SetBit - void US_Triger_SetBit(byte Bit);
**         ClrBit - void US_Triger_ClrBit(byte Bit);
**         NegBit - void US_Triger_NegBit(byte Bit);
**
**     Copyright : 1997 - 2012 Freescale, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __US_Triger_H
#define __US_Triger_H

/* MODULE US_Triger. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "BitsIoLdd2.h"

#include "Cpu.h"




/*
** ===================================================================
**     Method      :  US_Triger_GetDir (component BitsIO)
**
**     Description :
**         This method returns direction of the component.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the component (always TRUE, Output only)
**                      FALSE = Input, TRUE = Output
** ===================================================================
*/
#define US_Triger_GetDir() (BitsIoLdd2_GetDir(BitsIoLdd2_DeviceData))

/*
** ===================================================================
**     Method      :  US_Triger_GetVal (component BitsIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 15)
** ===================================================================
*/
#define US_Triger_GetVal() ((byte)BitsIoLdd2_GetVal(BitsIoLdd2_DeviceData))

/*
** ===================================================================
**     Method      :  US_Triger_PutVal (component BitsIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 15)
**     Returns     : Nothing
** ===================================================================
*/
#define US_Triger_PutVal(Val) (BitsIoLdd2_PutVal(BitsIoLdd2_DeviceData, ((dword)(Val))))

bool US_Triger_GetBit(byte Bit);
/*
** ===================================================================
**     Method      :  US_Triger_GetBit (component BitsIO)
**
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 3)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/

/*
** ===================================================================
**     Method      :  US_Triger_PutBit (component BitsIO)
**
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 3)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
#define US_Triger_PutBit(Bit,Val) ((void)BitsIoLdd2_PutBit(BitsIoLdd2_DeviceData, (Bit), (Val)))

/*
** ===================================================================
**     Method      :  US_Triger_SetBit (component BitsIO)
**
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
#define US_Triger_SetBit(Bit) ((void)BitsIoLdd2_SetBit(BitsIoLdd2_DeviceData, (Bit)))

/*
** ===================================================================
**     Method      :  US_Triger_ClrBit (component BitsIO)
**
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
#define US_Triger_ClrBit(Bit) ((void)BitsIoLdd2_ClrBit(BitsIoLdd2_DeviceData, (Bit)))

/*
** ===================================================================
**     Method      :  US_Triger_NegBit (component BitsIO)
**
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
#define US_Triger_NegBit(Bit) ((void)BitsIoLdd2_NegBit(BitsIoLdd2_DeviceData, (Bit)))

/* END US_Triger. */

#endif 
/* ifndef __US_Triger_H */
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
